### ISSUE TITLE
feat(exchange): change ask modal placeholder

### ISSUE THREAD

**Issue by douglasduteil** [toctocorg/toctoc#1265]
Depending of the exchange type, we should change the placeholder https://github.com/toctocorg/toctoc/blob/17b5294e8f218dc85f3d9edbb88ddbd841d73653/packages/%401/modules/exchange/ui/src/ask/form.tsx#L62 and the trigger button name https://github.com/toctocorg/toctoc/blob/17b5294e8f218dc85f3d9edbb88ddbd841d73653/apps/www/widgets/exchanges/card/actions.tsx#L41-L47
- [ ] for exchange proposition without returns, 
  - Button : `Demander`
  - Placeholder : `Bonjour, je veux bien une place.`
- [ ] for exchange research without returns, 
  - Button : `Répondre`
  - Placeholder : `Bonjour, je veux bien répondre a votre recherche.`
- [ ] for exchange research with returns, `Bonjour, je veux bien échanger avec toi.`
- [ ] for exchange proposition with returns, `Bonjour, je veux bien échanger avec toi.`

**Comment by JNSPK** [comment]
Is this by category or by pure type ? 

FI : Do you need to return a different placeholder if category is "Notes de cours || activité socio culturelle || ..." or just if this is "proposition || recherche" ?
