### ISSUE TITLE
feat(www): écriture inclusive

### ISSUE THREAD

**Issue by douglasduteil** [toctocorg/toctoc#1436]
- [x] replace "intéressé par" with "intéressé.e par"

**Comment by JNSPK** [comment]
Apaprently already done in #1446 

<p align =center>${\color{lightgreen}FIX}$ </p></p><p align=center><img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExazBiNnY3ZGY5MXFmMmZ3OHpoY2RlaDc1aXpkeXkwand0aGVwcGw5dSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/ggDy5NyLc8w0ZZPGFe/giphy.gif"></p>
